typography_spectrum: 0.8180927007924765
color:
  brandStrength: 0.2987770498730242
  lightness: 0.9957040084991604
  saturation: 0.49948898795992136
  rhythmicContrast: 0.9199843043461442
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
layout_spectrum: 0.49784558545798063
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/30dba59f-7063-499e-8fb7-2d7459edcde3.jpg
name: AccelEMR Solutions
navigation:
  - name: Who We Are
    id: f7c27626-2468-419b-a522-afd9aca128a7
    type: content
  - name: Our Products
    id: bf8ce18d-ee33-4cc2-b862-3ff45a9430c5
    type: content
  - name: Our Services
    id: 483c8c94-7426-4f00-aa7c-e67c21e34438
    type: content
  - name: Release 16.2
    id: cb67117c-3e5d-43e8-bdb5-dbff7f19a42e
    type: content
  - name: 'Testimonials '
    id: 076cd9dc-9018-4b6f-98b7-d027d0d7c9cf
    type: content
  - name: Request a Quote
    id: f3ff9aab-e1b5-4434-9c3e-8cd3f5427791
    type: content
  - name: Contact Us
    id: d6053454-7e74-4146-8752-fc9c52b4ac9b
    type: content
favicon: null
title: AccelEMR Solutions
description: Imagine. Innovate. Optimize.
